import { ProxyGroup, RulesetBehavior, RulesetFormat, RuleType, TunStack } from '@/enums/kernel'
import i18n from '@/lang'
import { generateSecureKey, sampleID } from '@/utils'

import type { ProfileType } from '@/stores'
import { DefaultTestURL } from './app'

const { t } = i18n.global

const DefaultOutboundIds = {
  Select: 'outbound-select',
  Urltest: 'outbound-urltest',
  Direct: 'outbound-direct',
  Block: 'outbound-block',
  Fallback: 'outbound-fallback',
  Global: 'outbound-global',
}

export const GeneralConfigDefaults = (): ProfileType['generalConfig'] => ({
  mode: 'rule',
  ipv6: true,
  'mixed-port': 20112,
  'allow-lan': false,
  'log-level': 'silent',
  'interface-name': '',
})

export const AdvancedConfigDefaults = (): ProfileType['advancedConfig'] => ({
  port: 0,
  'socks-port': 0,
  secret: generateSecureKey(),
  'external-controller': '127.0.0.1:20113',
  'external-ui': '',
  'keep-alive-interval': 30,
  'find-process-mode': 'strict',
  'external-controller-tls': '',
  'external-ui-name': '',
  'external-ui-url': '',
  'unified-delay': true,
  'tcp-concurrent': false,
  authentication: [],
  'skip-auth-prefixes': ['127.0.0.1/8', '::1/128'],
  tls: {
    certificate: '',
    'private-key': '',
  },
  'geodata-mode': false,
  'geo-auto-update': false,
  'geo-update-interval': 24,
  'geodata-loader': 'standard',
  'geosite-matcher': 'mph',
  'geox-url': {
    geoip: '',
    geosite: '',
    mmdb: '',
    asn: '',
  },
  'global-ua': 'chrome',
  profile: {
    'store-selected': true,
    'store-fake-ip': true,
  },
  'lan-allowed-ips': ['0.0.0.0/0', '::/0'],
  'lan-disallowed-ips': [],
})

export const TunConfigDefaults = (): ProfileType['tunConfig'] => ({
  enable: false,
  stack: TunStack.Mixed,
  'auto-route': true,
  'route-address': [],
  'route-exclude-address': [],
  'auto-detect-interface': true,
  'dns-hijack': ['any:53'],
  device: '',
  mtu: 0,
  'strict-route': true,
  'endpoint-independent-nat': false,
})

export const DnsConfigDefaults = (): ProfileType['dnsConfig'] => ({
  enable: true,
  listen: '',
  ipv6: true,
  'use-hosts': false,
  'use-system-hosts': true,
  'default-nameserver': [],
  nameserver: ['tls://8.8.8.8#' + t('kernel.proxyGroups.built-in.select')],
  'direct-nameserver': [],
  'proxy-server-nameserver': [],
  'nameserver-policy': {
    'rule-set:GEOSITE-CN': 'https://223.5.5.5/dns-query#' + t('kernel.proxyGroups.built-in.direct'),
    'rule-set:geolocation-!cn': 'tls://8.8.8.8#' + t('kernel.proxyGroups.built-in.select'),
  },
  'enhanced-mode': 'redir-host',
  'fake-ip-range': '198.18.0.1/16',
  'fake-ip-range6': 'fc00::/18',
  'fake-ip-filter-mode': 'blacklist',
  'fake-ip-filter': [
    '*.lan',
    '*.localdomain',
    '*.example',
    '*.invalid',
    '*.localhost',
    '*.test',
    '*.local',
    '*.home.arpa',
    '*.msftconnecttest.com',
    '*.msftncsi.com',
  ],
  fallback: [],
  'fallback-filter': {
    geoip: true,
    'geoip-code': 'CN',
    geosite: ['gfw'],
    ipcidr: ['240.0.0.0/4'],
    domain: ['+.google.com', '+.facebook.com', '+.youtube.com'],
  },
  'prefer-h3': false,
  hosts: {},
})

export const ProxyGroupsConfigDefaults = (): ProfileType['proxyGroupsConfig'] => {
  return [
    {
      id: DefaultOutboundIds.Select,
      name: t('kernel.proxyGroups.built-in.select'),
      type: ProxyGroup.Select,
      proxies: [
        {
          id: DefaultOutboundIds.Urltest,
          type: 'Built-In',
          name: t('kernel.proxyGroups.built-in.auto'),
        },
      ],
      url: '',
      interval: 300,
      strategy: 'consistent-hashing',
      use: [],
      tolerance: 150,
      lazy: true,
      'disable-udp': false,
      filter: '',
      'exclude-filter': '',
      hidden: false,
      icon: '',
    },
    {
      id: DefaultOutboundIds.Urltest,
      name: t('kernel.proxyGroups.built-in.auto'),
      type: ProxyGroup.UrlTest,
      proxies: [],
      url: DefaultTestURL,
      interval: 300,
      strategy: 'consistent-hashing',
      use: [],
      tolerance: 150,
      lazy: true,
      'disable-udp': false,
      filter: '',
      'exclude-filter': '',
      hidden: false,
      icon: '',
    },
    {
      id: DefaultOutboundIds.Direct,
      name: t('kernel.proxyGroups.built-in.direct'),
      type: ProxyGroup.Select,
      proxies: [
        { id: 'DIRECT', type: 'Built-In', name: 'DIRECT' },
        { id: 'REJECT', type: 'Built-In', name: 'REJECT' },
      ],
      url: '',
      interval: 300,
      strategy: 'consistent-hashing',
      use: [],
      tolerance: 150,
      lazy: true,
      'disable-udp': false,
      filter: '',
      'exclude-filter': '',
      hidden: false,
      icon: '',
    },
    {
      id: DefaultOutboundIds.Block,
      name: t('kernel.proxyGroups.built-in.reject'),
      type: ProxyGroup.Select,
      proxies: [
        { id: 'REJECT', type: 'Built-In', name: 'REJECT' },
        { id: 'DIRECT', type: 'Built-In', name: 'DIRECT' },
      ],
      url: '',
      interval: 300,
      strategy: 'consistent-hashing',
      use: [],
      tolerance: 150,
      lazy: true,
      'disable-udp': false,
      filter: '',
      'exclude-filter': '',
      hidden: false,
      icon: '',
    },
    {
      id: DefaultOutboundIds.Fallback,
      name: t('kernel.proxyGroups.built-in.fallback'),
      type: ProxyGroup.Select,
      proxies: [
        {
          id: DefaultOutboundIds.Select,
          type: 'Built-In',
          name: t('kernel.proxyGroups.built-in.select'),
        },
        {
          id: DefaultOutboundIds.Direct,
          type: 'Built-In',
          name: t('kernel.proxyGroups.built-in.direct'),
        },
      ],
      url: '',
      interval: 300,
      strategy: 'consistent-hashing',
      use: [],
      tolerance: 150,
      lazy: true,
      'disable-udp': false,
      filter: '',
      'exclude-filter': '',
      hidden: false,
      icon: '',
    },
    {
      id: DefaultOutboundIds.Global,
      name: 'GLOBAL',
      type: ProxyGroup.Select,
      proxies: [
        {
          id: DefaultOutboundIds.Select,
          type: 'Built-In',
          name: t('kernel.proxyGroups.built-in.select'),
        },
        {
          id: DefaultOutboundIds.Urltest,
          type: 'Built-In',
          name: t('kernel.proxyGroups.built-in.auto'),
        },
        {
          id: DefaultOutboundIds.Direct,
          type: 'Built-In',
          name: t('kernel.proxyGroups.built-in.direct'),
        },
        {
          id: DefaultOutboundIds.Block,
          type: 'Built-In',
          name: t('kernel.proxyGroups.built-in.reject'),
        },
        {
          id: DefaultOutboundIds.Fallback,
          type: 'Built-In',
          name: t('kernel.proxyGroups.built-in.fallback'),
        },
      ],
      url: '',
      interval: 300,
      strategy: 'consistent-hashing',
      use: [],
      tolerance: 150,
      lazy: true,
      'disable-udp': false,
      filter: '',
      'exclude-filter': '',
      hidden: false,
      icon: '',
    },
  ]
}

export const RulesConfigDefaults = (): ProfileType['rulesConfig'] => [
  {
    id: RuleType.InsertionPoint,
    type: RuleType.InsertionPoint,
    enable: true,
    payload: '',
    proxy: '',
    'no-resolve': false,
    'ruleset-name': '',
    'ruleset-type': 'file',
    'ruleset-behavior': RulesetBehavior.Domain,
    'ruleset-format': RulesetFormat.Mrs,
    'ruleset-proxy': '',
    'ruleset-interval': 0,
  },
  {
    id: sampleID(),
    type: RuleType.Logic,
    enable: true,
    payload: 'AND,((DST-PORT,443),(NETWORK,udp))',
    proxy: DefaultOutboundIds.Block,
    'no-resolve': false,
    'ruleset-name': '',
    'ruleset-type': 'file',
    'ruleset-behavior': RulesetBehavior.Domain,
    'ruleset-format': RulesetFormat.Mrs,
    'ruleset-proxy': DefaultOutboundIds.Direct,
    'ruleset-interval': 0,
  },
  {
    id: sampleID(),
    type: RuleType.RuleSet,
    enable: true,
    payload:
      'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-ads-all.mrs',
    proxy: DefaultOutboundIds.Block,
    'no-resolve': false,
    'ruleset-name': 'category-ads-all',
    'ruleset-type': 'http',
    'ruleset-behavior': RulesetBehavior.Domain,
    'ruleset-format': RulesetFormat.Mrs,
    'ruleset-proxy': DefaultOutboundIds.Direct,
    'ruleset-interval': 0,
  },
  {
    id: sampleID(),
    type: RuleType.RuleSet,
    enable: true,
    payload:
      'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/private.mrs',
    proxy: DefaultOutboundIds.Direct,
    'no-resolve': true,
    'ruleset-name': 'GEOIP-Private',
    'ruleset-type': 'http',
    'ruleset-behavior': RulesetBehavior.Ipcidr,
    'ruleset-format': RulesetFormat.Mrs,
    'ruleset-proxy': DefaultOutboundIds.Direct,
    'ruleset-interval': 0,
  },
  {
    id: sampleID(),
    type: RuleType.RuleSet,
    enable: true,
    payload: 'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/cn.mrs',
    proxy: DefaultOutboundIds.Direct,
    'no-resolve': true,
    'ruleset-name': 'GEOIP-CN',
    'ruleset-type': 'http',
    'ruleset-behavior': RulesetBehavior.Ipcidr,
    'ruleset-format': RulesetFormat.Mrs,
    'ruleset-proxy': DefaultOutboundIds.Direct,
    'ruleset-interval': 0,
  },
  {
    id: sampleID(),
    type: RuleType.RuleSet,
    enable: true,
    payload:
      'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/private.mrs',
    proxy: DefaultOutboundIds.Direct,
    'no-resolve': false,
    'ruleset-name': 'GEOSITE-Private',
    'ruleset-type': 'http',
    'ruleset-behavior': RulesetBehavior.Domain,
    'ruleset-format': RulesetFormat.Mrs,
    'ruleset-proxy': DefaultOutboundIds.Direct,
    'ruleset-interval': 0,
  },
  {
    id: sampleID(),
    type: RuleType.RuleSet,
    enable: true,
    payload: 'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/cn.mrs',
    proxy: DefaultOutboundIds.Direct,
    'no-resolve': false,
    'ruleset-name': 'GEOSITE-CN',
    'ruleset-type': 'http',
    'ruleset-behavior': RulesetBehavior.Domain,
    'ruleset-format': RulesetFormat.Mrs,
    'ruleset-proxy': DefaultOutboundIds.Direct,
    'ruleset-interval': 0,
  },
  {
    id: sampleID(),
    type: RuleType.RuleSet,
    enable: true,
    payload:
      'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/geolocation-!cn.mrs',
    proxy: DefaultOutboundIds.Select,
    'no-resolve': false,
    'ruleset-name': 'geolocation-!cn',
    'ruleset-type': 'http',
    'ruleset-behavior': RulesetBehavior.Domain,
    'ruleset-format': RulesetFormat.Mrs,
    'ruleset-proxy': DefaultOutboundIds.Direct,
    'ruleset-interval': 0,
  },
  {
    id: sampleID(),
    type: RuleType.Match,
    enable: true,
    payload: '',
    proxy: DefaultOutboundIds.Fallback,
    'no-resolve': false,
    'ruleset-name': '',
    'ruleset-type': 'file',
    'ruleset-behavior': RulesetBehavior.Domain,
    'ruleset-format': RulesetFormat.Mrs,
    'ruleset-proxy': DefaultOutboundIds.Direct,
    'ruleset-interval': 0,
  },
]

export const SnifferDefaults = (): ProfileType['sniffer'] => ({
  enable: true,
  'force-dns-mapping': true,
  'parse-pure-ip': true,
  'override-destination': false,
  'force-domain': [],
  'skip-domain': [],
  'skip-src-address': [],
  'skip-dst-address': [],
  sniff: {
    HTTP: {
      enable: true,
      ports: ['80', '8080-8880'],
    },
    TLS: {
      enable: true,
      ports: ['443', '8443'],
    },
    QUIC: {
      enable: true,
      ports: ['443', '8443'],
    },
  },
})

export const MixinConfigDefaults = (): ProfileType['mixinConfig'] => {
  return { priority: 'mixin', format: 'json', config: '' }
}

export const ScriptConfigDefaults = (): ProfileType['scriptConfig'] => {
  return { code: `const onGenerate = async (config) => {\n  return config\n}` }
}
