// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Download(arg1, arg2) {
  return window['go']['main']['App']['Download'](arg1, arg2);
}

export function Exec(arg1, arg2) {
  return window['go']['main']['App']['Exec'](arg1, arg2);
}

export function GetAppName() {
  return window['go']['main']['App']['GetAppName']();
}

export function GetInterfaces() {
  return window['go']['main']['App']['GetInterfaces']();
}

export function GetSystemProxy() {
  return window['go']['main']['App']['GetSystemProxy']();
}

export function HttpGet(arg1, arg2) {
  return window['go']['main']['App']['HttpGet'](arg1, arg2);
}

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function Movefile(arg1, arg2) {
  return window['go']['main']['App']['Movefile'](arg1, arg2);
}

export function ProcessInfo(arg1) {
  return window['go']['main']['App']['ProcessInfo'](arg1);
}

export function Readfile(arg1) {
  return window['go']['main']['App']['Readfile'](arg1);
}

export function Removefile(arg1) {
  return window['go']['main']['App']['Removefile'](arg1);
}

export function SetSystemProxy(arg1, arg2) {
  return window['go']['main']['App']['SetSystemProxy'](arg1, arg2);
}

export function StartKernel(arg1, arg2) {
  return window['go']['main']['App']['StartKernel'](arg1, arg2);
}

export function UnzipZIPFile(arg1, arg2) {
  return window['go']['main']['App']['UnzipZIPFile'](arg1, arg2);
}

export function Writefile(arg1, arg2) {
  return window['go']['main']['App']['Writefile'](arg1, arg2);
}
